def footer():
    result  = '<footer class="page-footer font-small teal pt-4 bg-dark">'
    result += '<div class="container-fluid text-center text-sm-left">'
    result +='<div class="row">'
    result += '<div class="col-sm-6 mt-sm-0 mt-3">'
    result += '<h5 style="color: white;" class="text-uppercase font-weight-bold">Footer text 1</h5>'
    result += '<p style="color: white;">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil'
    result += 'repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae'
    result += 'harum esse fugiat. Itaque, culpa?'
    result += '</p>'
    result += '</div>'
    result += '<hr class="clearfix w-100 d-sm-none pb-3">'
    result += '<div class="col-sm-6 mb-sm-0 mb-3">'
    result += '<h5 style="color: white;" class="text-uppercase font-weight-bold">Footer text 2</h5>'
    result += '<p style="color: white;">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Optio deserunt fuga perferendis modi earum'
    result += 'commodi aperiam temporibus quod nulla nesciunt aliquid debitis ullam omnis quos ipsam, aspernatur id'
    result += 'excepturi hic.'
    result += '</p>'
    result += '</div>'
    result += '</div>'
    result += '</div>'
    result += '<div style="color: white; background-color: rgb(31, 33, 33);" class="footer-copyright text-center py-3"> © 2020 Copyright| '
    result += '<a href="#">groupe05</a>'
    result += '</div>'
    result += '</footer>'
    return result
